AppBundle\Entity\Citizen:
    type: entity
    table: citizen
    indexes:
        city_id:
            columns:
                - city_id
        friend:
            columns:
                - friend
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        city:
            targetEntity: City
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                city_id:
                    referencedColumnName: id
            orphanRemoval: false
        friend:
            targetEntity: Citizen
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                friend:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
